#server
server:
  port: 8888

# mybatis
mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.domaji.erd.deposit.dto, com.domaji.erd.savings.dto, com.domaji.erd.card.dto, com.domaji.erd.customer.dto, com.domaji.erd.account.dto
  configuration:
    map-underscore-to-camel-case: true

#database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ERD?characterEncoding=utf8
    username: root
    password: mysql
